#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-25
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

dm_list=(5 10 15 20 25)
# sp_list=(1 2 4 8 16)
# dm_list=(15 18 21 24 27)
sp_list=(1 3 5 7 9)

len1=${#dm_list[@]}
len2=${#sp_list[@]}
iid=$SLURM_ARRAY_TASK_ID

jdm=$(($iid%$len1))
[[ $jdm == 0 ]] && jdm=$len1
jsp=$((($iid+$len1-1)/$len1))

echo $dm_list[$jdm]
echo $sp_list[$jsp]

./condonly_4m.zsh $dm_list[$jdm] $sp_list[$jsp]
