#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-25
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

dm_list=(15 18 21 24 27)
sp_list=(1 3 5 7 9)

len1=${#dm_list[@]}
len2=${#sp_list[@]}
iid=$SLURM_ARRAY_TASK_ID

ja=$(($iid%$len1))
[[ $ja == 0 ]] && ja=$len1
jw=$((($iid+$len1-1)/$len1))

echo $dm_list[$ja]
echo $sp_list[$jw]

./condcoll_mod.zsh $dm_list[$ja] $sp_list[$jw]
