#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-25
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

mc_list=(0.0002 0.0004 0.0006 0.0008 0.001)
sp_list=(1 3 5 7 9)

len1=${#mc_list[@]}
len2=${#sp_list[@]}
iid=$SLURM_ARRAY_TASK_ID

jmc=$(($iid%$len1))
[[ $jmc == 0 ]] && jmc=$len1
jsp=$((($iid+$len1-1)/$len1))

echo $mc_list[$jmc]
echo $sp_list[$jsp]

./collonly.zsh $mc_list[$jmc] $sp_list[$jsp]
