#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-8400
#SBATCH -o job_outs/KiD-%A-%a.out
#SBATCH -e job_outs/KiD-%A-%a.out
#SBATCH -t 00:04:00
#SBATCH -p med2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID
iid=$SLURM_ARRAY_TASK_ID

mom1_list=(1 2 4)
mom2_list=(1 2 4 5 6 7 8 9)

for (( i1 = 1; i1 <= ${#mom1_list[@]}; i1++ )); do
   for (( i2 = 1; i2 <= ${#mom2_list[@]}; i2++ )); do
      if [[ $i1 -ne $i2 ]]; then
         momcombo+=(${mom1_list[i1]}${mom2_list[i2]})
      fi
   done
done

len1=${#momcombo[@]}
imomc=$(($iid%$len1))
[[ $imomc == 0 ]] && imomc=$len1
momc=$momcombo[$imomc]
mom1=$momc[1]
mom2=$momc[2]

# Read the raining cases list
# Set the delimiter to a comma
IFS=','

# Define the name of the CSV file
csv_file="sp_combo.csv"

# Read the CSV file
while read -r var1 var2; do
  spc_list+=("$var1")
  spr_list+=("$var2")
done < "$csv_file"

len2=${#spc_list[@]}
isp=$(( ($iid - 1)/$len1 +1 ))

# Define the name of the CSV file
csv_file="raining_cases.csv"

# Read the CSV file
while read -r var1 var2; do
  w_list+=("$var1")
  a_list+=("$var2")
done < "$csv_file"

iaw=$(( ($iid - 1)/($len1*$len2) +1 ))


./fullmic_conftest.zsh $mom1 $mom2 $spc_list[$isp] $spr_list[$isp] $a_list[$iaw] $w_list[$iaw]
