#!/bin/zsh

a_list=(50 100 200 400)
w_list=(0.5 1 2 4)

len1=${#a_list[@]}
len2=${#w_list[@]}

nruns=$(($len1*$len2))

for (( iid = 1; iid <= nruns; iid++ )); do

ja=$(($iid%$len1))
[[ $ja == 0 ]] && ja=$len1
jw=$((($iid+$len1-1)/$len1))

echo $ja $a_list[$ja]
echo $jw $w_list[$jw]

./boss_amp_comp.zsh $a_list[$ja] $w_list[$jw] &
done
