#!/bin/zsh

dm_list=(50 100 200 300 400 500 600 700 800 900 1000)
nu_list=(2 4 6 8 10 12 14)

len1=${#dm_list[@]}
len2=${#nu_list[@]}

nruns=$(($len1*$len2))

for (( iid = 1; iid <= nruns; iid++ )); do

jdm=$(($iid%$len1))
[[ $jdm == 0 ]] && jdm=$len1
jnu=$((($iid+$len1-1)/$len1))

echo $dm_list[$jdm] $nu_list[$jnu]

./target_rainshaft.zsh $dm_list[$jdm] $nu_list[$jnu] &
done
