#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-10
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 1:00:00
#SBATCH -p med2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

cm_list=(.8 .9 0.95 0.975 0.9875 0.99375 0.996875 0.9984375 0.99921875 1.)
dmr_list=(30)

len1=${#cm_list[@]}
len2=${#dmr_list[@]}
iid=$SLURM_ARRAY_TASK_ID

jcm=$(($iid%$len1))
[[ $jcm == 0 ]] && jcm=$len1
jdmr=$((($iid+$len1-1)/$len1))

echo $cm_list[$jcm]
echo $dmr_list[$jdmr]

./collonly_vcm_4m.zsh $cm_list[$jcm] $dmr_list[$jdmr]
