#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-16
#SBATCH -o job_outs/KiD-%A-%a.out
#SBATCH -e job_outs/KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

a_list=(100 200 400 800)
w_list=(2 4 8 16)

len1=${#a_list[@]}
len2=${#w_list[@]}
iid=$SLURM_ARRAY_TASK_ID

ja=$(($iid%$len1))
[[ $ja == 0 ]] && ja=$len1
jw=$((($iid+$len1-1)/$len1))

echo $a_list[$ja]
echo $w_list[$jw]

./fullmic_4m.zsh $a_list[$ja] $w_list[$jw] 3
