#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-25
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

dm_list=(15 18 21 24 27)
rh_list=(0.3 0.5 0.6 0.7 0.74)
# sp_list=(1 3 5 7 9)

len1=${#dm_list[@]}
len2=${#rh_list[@]}
iid=$SLURM_ARRAY_TASK_ID

jdm=$(($iid%$len1))
[[ $jdm == 0 ]] && jdm=$len1
jrh=$((($iid+$len1-1)/$len1))

echo $dm_list[$jdm]
echo $rh_list[$jrh]

./collsedevap.zsh $dm_list[$jdm] $rh_list[$jrh]
# ./collsedevap_mod.zsh $dm_list[$jdm] $sp_list[$jsp]
