#!/bin/zsh

dm_list=(200 400 600)
sp_list=(4)

len1=${#dm_list[@]}
len2=${#sp_list[@]}
nruns=$(($len1*$len2))

nens=146

for (( iens = 1; iens <= nens; iens++ )); do
  
for (( iid = 1; iid <= nruns; iid++ )); do

jdm=$(($iid%$len1))
[[ $jdm == 0 ]] && jdm=$len1
jsp=$((($iid+$len1-1)/$len1))

echo $jdm $dm_list[$jdm]
echo $jsp $sp_list[$jsp]

./fall1l.zsh $dm_list[$jdm] $sp_list[$jsp] $iens
done

done
