#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-25
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

dm_list=(200 400 600 800 1000)
dz_list=(2000 3000 4000 5000 6000)

len1=${#dm_list[@]}
len2=${#dz_list[@]}
iid=$SLURM_ARRAY_TASK_ID

jdm=$(($iid%$len1))
[[ $jdm == 0 ]] && jdm=$len1
jdz=$((($iid+$len1-1)/$len1))

echo $dm_list[$jdm]
echo $dz_list[$jdz]

./sedonly_4m.zsh $dm_list[$jdm] $dz_list[$jdz]
