#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-5376
#SBATCH -o job_outs/KiD-%A-%a.out
#SBATCH -e job_outs/KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p med2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID
iid=$SLURM_ARRAY_TASK_ID

mom1_list=(1 2 4 5 6 7 8 9)
mom2_list=(1 2 4 5 6 7 8 9)
sp_list=(1 4 6 8 10 12)


# Read the raining cases list
# Set the delimiter to a comma
IFS=','

# Define the name of the CSV file
csv_file="raining_cases.csv"

# Read the CSV file
while read -r var1 var2; do
  w_list+=("$var1")
  a_list+=("$var2")
done < "$csv_file"

iaw=$(( ($iid-1)/336 +1 ))


for (( i1 = 1; i1 <= ${#mom1_list[@]}; i1++ )); do
   for (( i2 = 1; i2 <= ${#mom2_list[@]}; i2++ )); do
      if [[ $i1 -ne $i2 ]]; then
         momcombo+=(${mom1_list[i1]}${mom2_list[i2]})
      fi
   done
done

len1=${#momcombo[@]}
len2=${#sp_list[@]}

imomc=$(($iid%$len1))
[[ $imomc == 0 ]] && imomc=$len1
isp=$(((($iid+$len1-1)/$len1)%6))
[[ $isp == 0 ]] && isp=$len2

momc=$momcombo[$imomc]
mom1=$momc[1]
mom2=$momc[2]

./fullmic_conftest.zsh $mom1 $mom2 $sp_list[$isp] $a_list[$iaw] $w_list[$iaw]
