#!/bin/zsh

alist=(50 100 200 400)
wlist=(0.5 1 2 4)

len1=${#alist[@]}
len2=${#wlist[@]}

nruns=$(($len1*$len2))

for (( iid = 1; iid <= nruns; iid++ )); do

jdm=$(($iid%$len1))
[[ $jdm == 0 ]] && jdm=$len1
jsp=$((($iid+$len1-1)/$len1))

# echo $jdm $alist[$jdm]
# echo $jsp $wlist[$jsp]

./condcoll.zsh $alist[$jdm] $wlist[$jsp] &
done
