#!/bin/bash -l
#SBATCH -J KiD
#SBATCH -o KiD-%j.out
#SBATCH -e KiD-%j.err
#SBATCH -t 6:00:00
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

./run_bin_tests.sh
