#!/bin/bash -l
#SBATCH -J KiD
#SBATCH -o KiD-%j.out
#SBATCH -e KiD-%j.err
#SBATCH -t 6:00:00
#SBATCH -p high2
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

for iw in 8 16
do
   for ia in 800 1600
   do
      ./cond_only.zsh $iw $ia >& out&
   done
done
