#!/bin/bash
#PBS -N KiD_AMP
#PBS -A UCDV0021
#PBS -l walltime=06:00:00
#PBS -q share
#PBS -j oe
#PBS -m abe
#PBS -M azqhu@ucdavis.edu
#PBS -l select=1:ncpus=1:mpiprocs=1
### Set TMPDIR as recommended
setenv TMPDIR /glade/scratch/$USER/temp
mkdir -p $TMPDIR

### Run the executable
./run_nuc_tests.sh
