#!/bin/zsh
#SBATCH -J KiD
#SBATCH --array=1-25
#SBATCH -o KiD-%A-%a.out
#SBATCH -e KiD-%A-%a.out
#SBATCH -t 24:00:00
#SBATCH -p high
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mail-type=END
#SBATCH --mail-user=azqhu@ucdavis.edu

echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

spc_list=(1 4 8 12 20)
spr_list=(1 4 8 12 20)

len1=${#spc_list[@]}
len2=${#spr_list[@]}
iid=$SLURM_ARRAY_TASK_ID

jspc=$(($iid%$len1))
[[ $jspc == 0 ]] && jspc=$len1
jspr=$((($iid+$len1-1)/$len1))

echo $spc_list[$jspc]
echo $spr_list[$jspr]

./condcoll_2m.zsh $spc_list[$jspc] $spr_list[$jspr]
